# Generated by Django 5.0.3 on 2024-03-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('car_year', models.IntegerField()),
                ('car_image', models.ImageField(upload_to='static/cars')),
                ('car_price', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('case_phone', models.CharField(max_length=10)),
                ('c_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.cars')),
            ],
        ),
    ]
